#!/bin/bash
due=$1
file="$1"_todo.note
touch $file
echo "-- $(date)">> $file
echo "DESCRIPTION">> $file
echo "    DUE_DATE:                     $1">> $file
echo >> $file
echo "    LINK" >> $file
echo "    -- here list of cases" >> $file
echo >> $file
echo "    TARGET" >> $file
echo "    -- here expected result:">> $file
echo >> $file
echo "TODO">> $file
echo "   complete target                 TODO" >> $file
echo "SUMMARY">> $file
echo "   -- This task summary">> $file
echo done
