#!/usr/bin/env bash
 
var1=$1
var2=$2
  
var1=${var1:=$(date +%F)}
var2=${var2:=$(date +%F)}
   
if [[ $(date +%s -d"$var1") -ge $(date +%s -d"$var2") ]]; then
    str="ago"
fi
          
planning day $var1
mv day_plan.note "$var1"_todo.note
until [[ "$var1" == "$var2" ]]; do
    var1=$(date +%F -d"$var1 1 days $str")
    planningfromtemplate day $var1
    mv day_plan.note "$var1"_todo.note
done
