#!/bin/bash
file=week_plan_"$1".note
id=$(date +%s%N)
touch $file
echo -- id $id >> $file
echo -- $(date)>> $file
echo DESCRIPTION>> $file
echo "    TYPE_OF_PLAN:                 WEEK" >> $file
echo "    START_DATE:                   "$1"" >> $file
echo "    END_DATE:                     "$2"" >> $file
echo >> $file
echo LINK >> $file
echo "    -- here list of cases" >> $file
echo >> $file
echo GOAL >> $file
echo "    -- here list of goals" >> $file
echo >> $file
echo TODO >> $file
echo "                   MON  TUE  WED  THU  FRI  SAT  SUN">> $file
echo " ------------------------------------------------------" >> $file
echo " Some todo         TODO TODO TODO TODO TODO TODO TODO" >> $file
echo " ------------------------------------------------------" >> $file
echo "                   MON  TUE  WED  THU  FRI  SAT  SUN" >> $file
echo "SUMMARY" >> $file
echo "    -- This is a week summary" >> $file
echo >> $file
vim $file
